medic/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from django.conf.urls.static import static
admin.autodiscover()
import settings
urlpatterns = patterns('',
    url(r'^$', 'medic.views.home', name='home'),
    # url(r'^medic/', include('medic.foo.urls')),
    url(r'^tags/(?P<pk>[0-9]+)/$',"medic.views.tags",name="patient_tag"),
    url(r'^patdb/', include('patdb.urls',namespace='patdb')),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
	url(r'^accounts/', include('registration.backends.default.urls')),
	url(r'^login$', 'django.contrib.auth.views.login', {'template_name': 'login.html'},name="login"),
	url(r'^logout$', 'django.contrib.auth.views.logout', {'template_name': 'logout.html'},name="logout"),
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

patdb/urls.py
from django.conf.urls.defaults import *
from views import PatientListView, PatientUpdateView, PatientCreateView, PatientDeleteView , PatientDetailView

patient_patterns= patterns('',
    url(r'^list/page(?P<page>[0-9]+)/(\?.*)?$', 
        PatientListView.as_view(),
        name='list'),
    url(r'^update/(?P<pk>\d+)/$', 
        PatientUpdateView.as_view(),
        name='update'),
    url(r'^create/$', 
        PatientCreateView.as_view(),
        name='create'),
    url(r'^delete/(?P<pk>[0-9]+)/$', 
        PatientDeleteView.as_view(),
        name='delete'),
    url(r'^view/(?P<pk>[0-9]+)/$',PatientDetailView.as_view(),name="view"),
)

newpatterns = patterns('',
    url(r'^patient/', include(patient_patterns, namespace="patient")),
)

try:
    urlpatterns+=newpatterns
except NameError:
    urlpatterns=newpatterns
from django.conf.urls.defaults import *
from views import PatientInterviewListView, PatientInterviewUpdateView, PatientInterviewCreateView, PatientInterviewDeleteView ,PatientInterviewDetailView

patientinterview_patterns= patterns('',
    url(r'^list/page(?P<page>[0-9]+)/(\?.*)?$', 
        PatientInterviewListView.as_view(),
        name='list'),
    url(r'^update/(?P<pk>\d+)/$', 
        PatientInterviewUpdateView.as_view(),
        name='update'),
    url(r'^create/$', 
        PatientInterviewCreateView.as_view(),
        name='create'),
    url(r'^delete/(?P<pk>[0-9]+)/$', 
        PatientInterviewDeleteView.as_view(),
        name='delete'),
     url(r'^view/(?P<pk>[0-9]+)/$',PatientInterviewDetailView.as_view(),name="view"),
)

newpatterns = patterns('',
    url(r'^patientinterview/', include(patientinterview_patterns, namespace="patientinterview")),
)

try:
    urlpatterns+=newpatterns
except NameError:
    urlpatterns=newpatterns
from django.conf.urls.defaults import *
from views import ObservationFileListView, ObservationFileUpdateView, ObservationFileCreateView, ObservationFileDeleteView

observationfile_patterns= patterns('',
    url(r'^list/page(?P<page>[0-9]+)/(\?.*)?$', 
        ObservationFileListView.as_view(),
        name='list'),
    url(r'^update/(?P<pk>\d+)/$', 
        ObservationFileUpdateView.as_view(),
        name='update'),
    url(r'^create/$', 
        ObservationFileCreateView.as_view(),
        name='create'),
    url(r'^delete/(?P<pk>[0-9]+)/$', 
        ObservationFileDeleteView.as_view(),
        name='delete'),
)

newpatterns = patterns('',
    url(r'^observationfile/', include(observationfile_patterns, namespace="observationfile")),
)

try:
    urlpatterns+=newpatterns
except NameError:
    urlpatterns=newpatterns

patdb/models.py
from django.db import models
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
class Profile(models.Model):
	user = models.OneToOneField(User)
	address = models.TextField(blank=True)
	phoneNumber = models.CharField(blank=True, max_length=80)
GENDER=((1,"MALE"),(2,"FEMALE"))
BLOODTYPE=((1,"A"),(2,"B"),(3,"AB"),(4,"O"))	
class Patient(models.Model):
	firstName = models.CharField(blank=True, max_length=80)
	lastName = models.CharField(blank=False, max_length=80)
	dateOfBirth = models.DateField(blank=False, null=True, auto_now_add=True)
	physicalAddress = models.CharField(blank=True, max_length=80,null=True)
	phoneNumber = models.CharField(blank=False, max_length=80)
	alternatePhoneNumber = models.CharField(blank=True, max_length=80, null=True)
	maritalStatus = models.CharField(blank=True, max_length=80)
	emailAddress = models.EmailField()
	created = models.DateTimeField(blank=True, null=True, auto_now_add=True)
	photo = models.FileField(upload_to="pats", null=True)
	sex = models.IntegerField(choices=GENDER)
	bloodType = models.IntegerField( null=True,choices=BLOODTYPE)
	height = models.FloatField()
	weight = models.FloatField()
	alergies = models.TextField(blank=True)
	nextOfKinContact = models.TextField(blank=True)
	tags = TaggableManager()
	def __unicode__(self):
		return self.firstName +" " +self.lastName
	def interviews(self):
		return PatientInterview.objects.filter(patient__id=self.id)
class PatientInterview(models.Model):
	patient = models.OneToOneField(Patient)
	created = models.DateTimeField(blank=True, null=True, auto_now_add=True)
	problemPresentedByPatient = models.TextField(blank=True, null=True)
	observations = models.TextField(blank=True, null=True)
	examinations = models.TextField(blank=True, null=True)
	diagnosis = models.TextField(blank=True, null=True)
	treatmentGiven = models.TextField(blank=True, null=True)
	extraRemarks = models.TextField(blank=True, null=True)
	def __unicode__(self):
		return self.patient.firstName +" " +self.patient.lastName +" on "+ str(self.created.date())
	
class ObservationFile(models.Model):
	patientInterview = models.OneToOneField(PatientInterview)
	file = models.FileField(upload_to="pats")
	fileType = models.CharField(blank=True, max_length=80)
	created = models.DateTimeField(blank=True, null=True, auto_now_add=True)

medic/views.py
from django.http import HttpResponse
from django.shortcuts import render_to_response
from django.template import RequestContext
from taggit.models import Tag
from patdb.models import Patient
def home(request):
	return render_to_response( 'index.html', {}, context_instance=RequestContext(request))
def tags(request,pk):
	tag = Tag.objects.get(pk=pk)
	patients =Patient.objects.filter(tags__pk=pk)
	return render_to_response( 'tagged.html', {"tag":tag,"patients":patients}, context_instance=RequestContext(request))

patdb/views.py
#crudgenerator auto-generated code.
#crudgenetaror date: 11th August 2012 11:11
from django.core.urlresolvers import reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView , DetailView
from models import Patient

class PatientDetailView(DetailView):
    model=Patient
class PatientListView(ListView):
    model=Patient
    paginate_by=20

class PatientDeleteView(DeleteView):
    model=Patient
    def get_success_url(self):
        return reverse("patdb:patient:list", args=(1,))

class PatientCreateView(CreateView):
    model=Patient
    def get_success_url(self):
        return reverse("patdb:patient:list", args=(1,))

class PatientUpdateView(UpdateView):
    model=Patient
    def get_success_url(self):
        return reverse("patdb:patient:list", args=(1,))
#crudgenerator auto-generated code.
#crudgenetaror date: 11th August 2012 11:12
from django.core.urlresolvers import reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from models import PatientInterview


class PatientInterviewListView(ListView):
    model=PatientInterview
    paginate_by=20
class PatientInterviewDetailView(DetailView):
    model=PatientInterview
class PatientInterviewDeleteView(DeleteView):
    model=PatientInterview
    def get_success_url(self):
        return reverse("patdb:patientinterview:list", args=(1,))

class PatientInterviewCreateView(CreateView):
    model=PatientInterview
    def get_success_url(self):
        return reverse("patdb:patientinterview:list", args=(1,))

class PatientInterviewUpdateView(UpdateView):
    model=PatientInterview
    def get_success_url(self):
        return reverse("patdb:patientinterview:list", args=(1,))
#crudgenerator auto-generated code.
#crudgenetaror date: 11th August 2012 11:12
from django.core.urlresolvers import reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from models import ObservationFile


class ObservationFileListView(ListView):
    model=ObservationFile
    paginate_by=20

class ObservationFileDeleteView(DeleteView):
    model=ObservationFile
    def get_success_url(self):
        return reverse("patdb:observationfile:list", args=(1,))

class ObservationFileCreateView(CreateView):
    model=ObservationFile
    def get_success_url(self):
        return reverse("patdb:observationfile:list", args=(1,))

class ObservationFileUpdateView(UpdateView):
    model=ObservationFile
    def get_success_url(self):
        return reverse("patdb:observationfile:list", args=(1,))

medic/templates/base.html
<!DOCTYPE html>
<html>
	<head>
		<title>MEDIC</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

		<link rel="stylesheet" href="{{ STATIC_URL }}css/bootstrap.min.css">
		<link rel="stylesheet" href="{{ STATIC_URL }}css/bootstrap-responsive.min.css" type="text/css" media="screen" charset="utf-8">
	</head>
	<body>
		<div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Patient DB</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li ><a href="{% url patdb:patient:list 1  %}">Patients</a></li>
              <li><a href="{% url patdb:patientinterview:list 1  %}">Interviews</a></li>
              <li><a href="{% url patdb:observationfile:list 1  %}">Observation Files</a></li>
            </ul>
            <ul class="nav pull-right">
              {% if user.is_authenticated %}
                <li>
                  <a href="{% url  logout  %}">Logout</a>
                </li>
              {% else %}
              <li>
                <a href="{% url  login  %}">Login</a>
              </li>{% endif %}</ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    <br>
    <br>
    <br>
    <br>
    <br>
    <div class="container">

     <div class="row">
     	{% block content %}
     		
     	{% endblock content %}
     </div>

    </div> <!-- /container -->
		
		<script src="{{ STATIC_URL }}js/jquery.min.js"></script>
		
		<script src="{{ STATIC_URL }}js/bootstrap.min.js"></script>
	</body>
</html>

medic/templates/index.html
{% extends "base.html" %}

medic/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block content %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

<form method="post" action="{% url django.contrib.auth.views.login %}">{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>
<p><a href="{% url auth_password_reset %}">Forgot</a> your password?  <a href="{% url registration_register %}">Need an account</a>?</p>

<input type="submit" value="login" />
<input type="hidden" name="next" value="/" />
</form>

{% endblock %}

medic/templates/login_base.html
<!DOCTYPE html>
<html>
	<head>
		<title>MEDIC</title>
		<link rel="stylesheet" href="{{ STATIC_URL }}css/bootstrap.min.css">
		<link rel="stylesheet" href="{{ STATIC_URL }}css/bootstrap-responsive.min.css" type="text/css" media="screen" charset="utf-8">
	</head>
	<body>
		<div class="navbar">
  				<div class="navbar-inner">
    				<div class="container">
						<a class="brand" href="#">
  							Patient DB
						</a>
						 
    				</div>
  				</div>
			</div>
		<div class="container">
			<div class="row">
				{% block content %}
					
				{% endblock content %}
			</div>
		</div>
		
		<script src="{{ STATIC_URL }}js/jquery.min.js"></script>
		
		<script src="{{ STATIC_URL }}js/bootstrap.min.js"></script>
	</body>
</html>

medic/templates/logout.html
{% extends "base.html" %}
{% block title %}Logged out{% endblock %}
{% block content %}
Successfully logged out!
{% endblock %}

medic/templates/tagged.html
{% extends "base.html" %}
{% block content %}

<h4>Patients Tagged {{tag}}</h4>
<table class="table table-stripped table-bordered">
	{% for patient in  patients %}
<tr>
		<td>
			 <a href="{% url patdb:patient:view patient.pk %}">{{patient}}</a></td>
		</td>
	</tr>
{% endfor %}
	
</table>


	
{% endblock content %}

medic/templates/temp.html
<!DOCTYPE html>
<html>
	<head>
		<title>MEDIC</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

		<link rel="stylesheet" href="{{ STATIC_URL }}css/bootstrap.min.css">
		<link rel="stylesheet" href="{{ STATIC_URL }}css/bootstrap-responsive.min.css" type="text/css" media="screen" charset="utf-8">
	</head>
	<body>
		<div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Project name</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="active"><a href="#">Home</a></li>
              <li><a href="#about">About</a></li>
              <li><a href="#contact">Contact</a></li>
            </ul>
            <ul class="nav pull-right">
              {% if user.is_authenticated %}
                <li>
                  <a href="{% url  logout  %}">Logout</a>
                </li>
              {% else %}
              <li>
                <a href="{% url  login  %}">Login</a>
              </li>{% endif %}</ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">

     <div class="row">
     	{% block django %}
     		
     	{% endblock django %}
     </div>

    </div> <!-- /container -->
		
		<script src="{{ STATIC_URL }}js/jquery.min.js"></script>
		
		<script src="{{ STATIC_URL }}js/bootstrap.min.js"></script>
	</body>
</html>

patdb/templates/patdb/observationfile_confirm_delete.html
{# coding: utf8 #}
{% extends "base.html" %}

{% block content %}

<div id="ObservationFile_confirm_delete_header" class="model-confirm-delete-header ObservationFile-confirm-delete-header">
Are you sure to delete "{{ object }}"?
</div>
<form action="." method="post" name="ObservationFile_delete" class="model-confirm-delete-form ObservationFile-confirm-delete-form">
    {% csrf_token %}
{{ form }}
    <div class="model-confirm-delete-buttons-bar ObservationFile-confirm-delete-buttons-bar">
        <input type="submit" value="Ok" class="model-confirm-delete-submitObservationFile-confirm-delete-submit"/>
        <a href="{% url patdb:observationfile:list page=1 %}" class="model-confirm-delete-form-cancel ObservationFile-confirm-delete-form-cancel">Cancel </a>
    </div>
</form>
{% endblock content %}

patdb/templates/patdb/observationfile_form.html
{# coding: utf8 #}
{% extends "base.html" %}

{% block content %}
{% load bootstrap_toolkit %}
{% if object %}
<div id="ObservationFile_form_header" class="object-form-header ObservationFile-form-header">
Editing {{object}}
</div>
{% else %}
Create new ObservationFile
{% endif %}
<form action="." method="post" name="ObservationFile_form" class="">
    {% csrf_token %}
    
            {{form|as_bootstrap}}
            
            <div class="actions">
        <button type="submit" class="btn primary">Submit</button>
        <a href="{% url patdb:observationfile:list 1  %}" class="btn">Cancel </a>
    </div>
      
</form>
{% endblock content %}

patdb/templates/patdb/observationfile_list.html
{# coding: utf8 #}
{% extends "base.html" %}

{% block content %}
<a href="{% url patdb:observationfile:create %}" class="model-new ObservationFile-new">New ObservationFile</a> 
{% if object_list %}
    <table class="table table-bordered table-stripped">
    <thead  >
        <tr class=" ">
            <th >ObservationFile </th> 
            <th > Actions</th> </tr>
    </thead>
    <tbody class="">
    {% for obj in object_list %}
        <tr >
            <td >{{obj}}</td>
            <td >
                <a href="{% url patdb:observationfile:update obj.pk %}" class="btn">edit</a>
                <a href="{% url patdb:observationfile:delete obj.pk %}" class="btn">delete</a>
            </td>
        </tr>
    {% endfor %}
    </tbody>
    </table>
    {% if is_paginated %}
        <div class="pagination">
             <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
            <ul>
                {% if page_obj.has_previous %}
                <li>
                    <a href="{% url patdb:observationfile:list page_obj.previous_page_number %}" >Previous</a>
                </li>
                    
                {% endif %}
               
                {% if page_obj.has_next %}
                <li>
                     <a href="{% url patdb:observationfile:list page_obj.next_page_number %}"  >Next</a>
                </li>
                   
                {% endif %}
            </ul>
        </div>
    {% endif %}
{% else %}
    <p id="observationfile_list_not_found_msg"  > No observationfiles found. </p>
{% endif %}

{% endblock content %}

patdb/templates/patdb/patient_confirm_delete.html
{# coding: utf8 #}
{% extends "base.html" %}

{% block content %}

<div id="Patient_confirm_delete_header" class="model-confirm-delete-header Patient-confirm-delete-header">
Are you sure to delete "{{ object }}"?
</div>
<form action="." method="post" name="Patient_delete" class="model-confirm-delete-form Patient-confirm-delete-form">
    {% csrf_token %}
{{ form }}
    <div class="model-confirm-delete-buttons-bar Patient-confirm-delete-buttons-bar">
        <input type="submit" value="Ok" class="model-confirm-delete-submitPatient-confirm-delete-submit"/>
        <a href="{% url patdb:patient:list page=1 %}" class="model-confirm-delete-form-cancel Patient-confirm-delete-form-cancel">Cancel </a>
    </div>
</form>
{% endblock content %}

patdb/templates/patdb/patient_detail.html
{% extends "base.html" %}
{% block content %}
	{% load taggit_extras %}
	<div class="row">
		<div class="span8">
			<h3>Patient Details</h3>
		</div>
		
	</div>
	<div class="row">
		<div class="span5">
			
		<table class="table table-stripped table-bordered">
			<tr>
				<td>
					<strong>First Name</strong>
				</td>
				<td>
					<span>{{object.firstName}}</span>
				</td>
			</tr>

			<tr>
				<td>
					<strong>Last Name</strong>
				</td>
				<td>
					<span>{{object.lastName}}</span>
				</td>
			</tr>

			<tr>
				<td>
					<strong>Date of Birth</strong>
				</td>
				<td>
					<span>{{object.dateOfBirth}}</span>
				</td>
			</tr>

			<tr>
				<td>
					<strong>Physical Address</strong>
				</td>
				<td>
					<span>{{object.physicalAddress}}</span>
				</td>
			</tr>
			<tr>
				<td>
					<strong>Phone Number</strong>
				</td>
				<td>
					<span>{{object.phoneNumber}}</span>
				</td>
			</tr>
			<tr>
				<td>
					<strong>Alternate Phone Number</strong>
				</td>
				<td>
					<span>{{object.alternatePhoneNumber}}</span>
				</td>
			</tr>
			<tr>
				<td>
					<strong>Marital Status</strong>
				</td>
				<td>
					<span>{{object.maritalStatus}}</span>
				</td>
			</tr>
			<tr>
				<td>
					<strong>Email Address</strong>
				</td>
				<td>
					<span>{{object.emailAddress}}</span>
				</td>
			</tr>
			<tr>
				<td>
					<strong>Sex</strong>
				</td>
				<td>
					<span>{{object.get_sex_display}}</span>
				</td>
			</tr>
			<tr>
				<td>
					<strong>Blood  Type</strong>
				</td>
				<td>
					<span>{{object.get_bloodType_display}}</span>
				</td>
			</tr>
			<tr>
				<td>
					<strong>Height</strong>
				</td>
				<td>
					<span>{{object.height}}</span>
				</td>
			</tr>
			<tr>
				<td>
					<strong>Weight</strong>
				</td>
				<td>
					<span>{{object.weight}}</span>
				</td>
			</tr>
			<tr>
				<td>
					<strong>Alergies</strong>
				</td>
				<td>
					<span>{{object.alergies}}</span>
				</td>
			</tr>
			<tr>
				<td>
					<strong>Next of Kin Contact</strong>
				</td>
				<td>
					<span>{{object.nextOfKinContact}}</span>
				</td>
			</tr>
		</table>
		</div>
		<div class="span4">
			<p>
				
<style type="text/css">
	.tag a{
		color:white;
	}
	.tag{
		margin:5px;
	}
</style>
<h4>Tags</h4>
{% for tag in object.tags.all %}

<span class="label label-info tag">
<a href="{% url patient_tag tag.id %}" class="">{{tag}}</a>
</span>
{% endfor %}

			</p>
			<p>
				<h4>Actions</h4>
				<a href="{% url patdb:patient:update object.pk %}" class="btn">edit</a>
                <a href="{% url patdb:patient:delete object.pk %}" class="btn">delete</a>
                <br/>
                <br>
			</p>
			 <p>
			 	<h4>Picture</h4>
			 	<a href="#" class="thumbnail">
				<img src="/media/{{object.photo}}" alt="">
			</a>
			 </p>
			
			<p>
				<h4>Interviews</h4>
				<a href="{% url patdb:patientinterview:create %}" class="model-new PatientInterview-new">New Patient Interview</a> 
				<table class="table table-stripped table-bordered">
					{% for interview in  object.interviews %}
					 	<tr>
						<td>
 <a href="{% url patdb:patientinterview:view interview.pk %}" >{{interview}}</a>
						</td>
					</tr>
					 	{% endfor %} 	
				
				</table>
			</p>
			
		</div>
		
	</div>
{% endblock content %}

patdb/templates/patdb/patient_form.html
{# coding: utf8 #}
{% extends "base.html" %}

{% block content %}

{% if object %}
<div id="Patient_form_header" class="object-form-header Patient-form-header">
Editing {{object}}
</div>
{% else %}
Create new Patient
{% endif %}
<form action="." method="post" enctype="multipart/form-data" name="Patient_form" class="">
    {% csrf_token %}
    {% load bootstrap_toolkit %}
            {{form|as_bootstrap}}
            
            <div class="actions">
        <button type="submit" class="btn primary">Submit</button>
        <a href="{% url patdb:patient:list 1  %}" class="btn">Cancel </a>
    </div>
      
</form>
{% endblock content %}

patdb/templates/patdb/patient_list.html
{# coding: utf8 #}
{% extends "base.html" %}

{% block content %}
<a href="{% url patdb:patient:create %}" class="model-new Patient-new">New Patient</a> 
{% if object_list %}
    <table class="table table-bordered table-stripped">
    <thead  >
        <tr class=" ">
            <th >Patient </th> 
            <th > Actions</th> </tr>
    </thead>
    <tbody class="">
    {% for obj in object_list %}
        <tr >
            <td >
                <a href="{% url patdb:patient:view obj.pk %}">{{obj}}</a></td>
            <td >
                <a href="{% url patdb:patient:update obj.pk %}" class="btn">edit</a>
                <a href="{% url patdb:patient:delete obj.pk %}" class="btn">delete</a>
            </td>
        </tr>
    {% endfor %}
    </tbody>
    </table>
    {% if is_paginated %}
        <div class="pagination">
             <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
            <ul>
                {% if page_obj.has_previous %}
                <li>
                    <a href="{% url patdb:patient:list page_obj.previous_page_number %}" >Previous</a>
                </li>
                    
                {% endif %}
               
                {% if page_obj.has_next %}
                <li>
                     <a href="{% url patdb:patient:list page_obj.next_page_number %}"  >Next</a>
                </li>
                   
                {% endif %}
            </ul>
        </div>
    {% endif %}
{% else %}
    <p id="patient_list_not_found_msg"  > No patients found. </p>
{% endif %}

{% endblock content %}

patdb/templates/patdb/patientinterview_confirm_delete.html
{# coding: utf8 #}
{% extends "base.html" %}

{% block content %}

<div id="PatientInterview_confirm_delete_header" class="model-confirm-delete-header PatientInterview-confirm-delete-header">
Are you sure to delete "{{ object }}"?
</div>
<form action="." method="post" name="PatientInterview_delete" class="model-confirm-delete-form PatientInterview-confirm-delete-form">
    {% csrf_token %}
{{ form }}
    <div class="model-confirm-delete-buttons-bar PatientInterview-confirm-delete-buttons-bar">
        <input type="submit" value="Ok" class="model-confirm-delete-submitPatientInterview-confirm-delete-submit"/>
        <a href="{% url patdb:patientinterview:list page=1 %}" class="model-confirm-delete-form-cancel PatientInterview-confirm-delete-form-cancel">Cancel </a>
    </div>
</form>
{% endblock content %}

patdb/templates/patdb/patientinterview_detail.html
{% extends "base.html" %}
{% block content %}
	<div class="row">
		<div class="span7">
			<a href="{% url patdb:patientinterview:create %}" class="model-new PatientInterview-new">New Patient Interview</a> 
			<table class="table table-stripped table-bordered">
				<tr>
					<td>
						<strong>Patient</strong>
					</td>
					<td>
						<span>
							{{object.patient}}
						</span>
					</td>
				</tr>
				<tr>
					<td>
						<strong>
							Date
						</strong>
					</td>
					<td>
						<span>
							{{object.created.date}}
						</span>
					</td>
				</tr>
				<tr>
					<td>
						<strong>Problems Presented</strong>
					</td>
					<td>
						<span>
							{{object.problemPresentedByPatient}}
						</span>
					</td>
				</tr>
				<tr>
					<td>
						<strong>Observations</strong>
					</td>
					<td>
						<span>
							{{object.observations}}
						</span>
					</td>
				</tr>
				<tr>
					<td>
						<strong>Examinations</strong>
					</td>
					<td>
						<span>
							{{object.examinations}}
						</span>
					</td>
				</tr>
				<tr>
					<td>
						<strong>Diagnosis</strong>
					</td>
					<td>
						<span>
							{{object.diagnosis}}
						</span>
					</td>
				</tr>

				<tr>
					<td>
						<strong>Treatment Given</strong>
					</td>
					<td>
						<span>
							{{object.treatmentGiven}}
						</span>
					</td>
				</tr>
				<tr>
					<td>
						<strong>Extra Remarks</strong>
					</td>
					<td>
						<span>
							{{object.extraRemarks}}
						</span>
					</td>
				</tr>

			</table>
		</div>
	</div>
{% endblock content %}